.test-vulnerabilities:
  stage: test-vulnerabilities
  image:
    name: registry.gitlab.com/passbolt/passbolt-ci-docker-images/aquasec:latest
  variables:
    TRIVY_USERNAME: $CI_REGISTRY_USER
    TRIVY_PASSWORD: $CI_REGISTRY_PASSWORD
    DOCKER_TAG: root
  script:
    - trivy image --ignore-unfixed $CI_REGISTRY_IMAGE:${PASSBOLT_FLAVOUR}-${DOCKER_TAG}-latest
  rules:
    - if: '($CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_MESSAGE =~ /test-image/ ) && $PASSBOLT_FLAVOUR =~ /ce|pro/'
      when: on_success

docker:
  extends: .test-vulnerabilities
docker-non-root:
  extends: .test-vulnerabilities
  variables:
    DOCKER_TAG: "rootless"
